Feature/1
mikhailalborisov/mytodo pull request #1
Opened 2022-10-13 19:15 UTC by mikhailalborisov

# ToDo list ( Список дел )

Одно из стандартных заданий для начинающего - приложение "список дел". Оно, как правило, проверяет совокупность усвоенных техник при работе с новым фреймворком.
Список дел - это приложение в котором пожно просматривать, создавать, изменять и удалять записи, которые являются описанием задач.
Например "помыть посуду", "вынести мусор" или "приготовить суп" - могут быть такими задачами.
Ваша задача - написать приложение для управления таким списком.

## Требования
- Хранить дела в БД, создать модель. обязательно должно быть описание задачи, дата создания задачи и статус (выполнено/не выполнено).
- Использовать стандартные View из джанго (ListView, CreateView, DetailView и другие). То есть при запросе в приложение из браузера будут страницы с отображением списка дел, страница отображением формы на добавление и изменение дела, кнопка на удаление дела из списка, кнопка на смену статуса дела.
- Все управление и отображение через html-шаблоны ( не json )
- Не должно быть секретных ключей и параметров соединения к БД в настройках (settings). Используйте django-environ
- Для отображения форм используйте django-crispy-forms
- Все зависимоти для проекта вместе с их версиями нужно поместить в requitrements.txt [pip freeze]
- Форматирование учитывается. Используйте black

2022-10-14 08:33 UTC, AABorisov commented on mytodoapp/models.py
> +    created_at = models.DateField(
`created_at = models.DateTimeField(auto_now_add=True)`
https://stackoverflow.com/a/3429915/2592323

2022-10-14 08:45 UTC, AABorisov commented on mytodoapp/models.py
> +    created_at = models.DateField(
Автоматическое выставление даты при создании
created_at = models.DateTimeField(auto_now_add=True)

Автоматическое выставление даты при update записи
updated_at = models.DateTimeField(auto_now=True)

2022-10-20 18:45 UTC, AllStar6581 commented on mytodoapp/admin.py
> +# Register your models here.
не удаленный комментарий

2022-10-20 18:50 UTC, AllStar6581 requested changes

2022-10-20 18:50 UTC, AllStar6581 commented on mytodoapp/admin.py
> +# Register your models here.
не удаленный комментарий

2022-10-20 18:50 UTC, AllStar6581 commented on mytodoapp/models.py
> +        blank=True,
Не пустое поле, нужно сделать автоматическое время создания = сейчас

2022-10-20 18:50 UTC, AllStar6581 commented on mytodoapp/models.py
> +        return reverse("todo-detail", kwargs={"pk": self.pk})
зачем здесь эта функция и почему в комментарии упоминаются книги?

2022-10-20 18:50 UTC, AllStar6581 commented on mytodoapp/templates/base.html
> +<!DOCTYPE html>
Шаблон нигде не используется и не наследуется

2022-10-20 18:50 UTC, AllStar6581 commented on mytodoapp/templates/index.html
> +<!DOCTYPE html>
Шаблон не используется и не наследуется

2022-10-20 18:50 UTC, AllStar6581 commented on mytodoapp/tests.py
> +from django.test import TestCase
Пустой файл, удалить

2022-10-29 19:03 UTC, mikhailalborisov commented on mytodoapp/models.py
> +        return reverse("todo-detail", kwargs={"pk": self.pk})
удалил

2022-10-29 19:03 UTC, mikhailalborisov commented on mytodoapp/models.py
> +        blank=True,
поправил

2022-10-29 19:03 UTC, mikhailalborisov commented on mytodoapp/admin.py
> +# Register your models here.
удалил

2022-10-29 19:04 UTC, mikhailalborisov commented on mytodoapp/models.py
> +    created_at = models.DateField(
поправил

2022-10-29 19:52 UTC, mikhailalborisov commented on mytodoapp/tests.py
> +from django.test import TestCase
удалил

2022-10-29 19:57 UTC, mikhailalborisov commented on mytodoapp/templates/index.html
> +<!DOCTYPE html>
удалил

2022-10-29 19:57 UTC, mikhailalborisov commented on mytodoapp/templates/base.html
> +<!DOCTYPE html>
удалил

2022-11-09 19:38 UTC, AllStar6581 approved these changes
все хорошо, можно мерджить!

2022-11-23 12:08 UTC, merged